"""Table added

Revision ID: 835cc09b1217
Revises: e801aaa2be95
Create Date: 2023-01-18 12:43:39.564696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835cc09b1217'
down_revision = 'e801aaa2be95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
