"""Table added

Revision ID: c56921e32e05
Revises: eaa914d4595a
Create Date: 2023-01-18 12:25:45.471735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56921e32e05'
down_revision = 'eaa914d4595a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'total_job',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'total_job',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
