"""Table added

Revision ID: de3bfff9d22c
Revises: 65e6965aa140
Create Date: 2023-01-18 17:43:15.051738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3bfff9d22c'
down_revision = '65e6965aa140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_job')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_job', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
