"""Table added

Revision ID: e801aaa2be95
Revises: c56921e32e05
Create Date: 2023-01-18 12:32:02.189615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e801aaa2be95'
down_revision = 'c56921e32e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
