"""Table added

Revision ID: e93b05d211f4
Revises: 835cc09b1217
Create Date: 2023-01-18 14:24:48.098834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93b05d211f4'
down_revision = '835cc09b1217'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
